### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#11]
See https://github.com/internet4000/radio4000/blob/master/LICENSE. Let's have something more permissive that restricts commercial use?

**Comment by hugurp** [comment]
why not GPLv3?
I don't really mind people using our work, if they do a better job, it's cool, if they use the project and do a worse job, it's cool.
In any case we'll have a good time here.

what I want is just that if people reuse this work, anyone can look at the code, learn, improve, share.

**Comment by oskarrough** [comment]
Yes!
