### ISSUE TITLE
channel.updated is updated for every change on channel model

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#110]
It used to be triggered only by new tracks, and now it is triggered by every change to a channel model.

How to reproduce? Add a new channel to your favorites, you will appear at the top of the channels list.

Maybe it is not a bug and actually better?

**Comment by oskarrough** [comment]
I vote it's better. Then we also do not have to worry about setting it ourselves.

**Comment by hugurp** [comment]
In term of privacy it is much more precise to trace a user usage of its radio.
So each time they favorite/unfavorite, add/edit a track or edit their radio, it will trigger an update of the `channel.lastUpdated` date.

When we used to have that update only when a track is added.

I think if we keep that we lose some privacy, and we lose an important data "when was a new track added to a radio".

**Comment by oskarrough** [comment]
Sure, that's also fair. So we either

- make a computed property ala `lastUpdated => this.tracks.lastObject.created`
- remove `timestamp` transform and manually set `updated` when we want (add track)

**Comment by hugurp** [comment]
If we make `lastUpdated` a computed property, we have to load all tracks to get the latest's created date.

We have to remember that the reason this changed is just that we had `NaN` print on the tracks grouping month.
The reason we want the last updated information is to sort channels by relevant activity.

**Comment by oskarrough** [comment]
True. To be honest I'm ok with how it is right now. Otherwise should we revert and go for solution b above?

**Comment by hugurp** [comment]
closing this for now as no answer emerged
