### ISSUE TITLE
Remove login route from history, after login success

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#121]
User story:
- am on a radio and want to add it as favorite, 
- need to login, and after thatam redirected to my radio (actual wanted behavior)
- if I click previous i am sent to the login route which i cannot access, since logged in
- therefore transition to login, and previous routes are always prevented

Comments
- would have liked the back button to bring me to the radio I wanted toadd as favorite
- maybe after login, the users should be redirected to the route they were on before

To be used: https://balinterdi.com/blog/replacing-items-in-browser-history-in-ember-dot-js/

**Comment by oskarrough** [comment]
https://guides.emberjs.com/v2.16.0/routing/preventing-and-retrying-transitions/#toc_storing-and-retrying-a-transition
