### ISSUE TITLE
Channel detail tabs break

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#125]
On `channel.index` the tabs do not work with long channel.title.

![screenshot from 2017-11-13 19-15-44](https://user-images.githubusercontent.com/1502484/32741706-71fb827a-c8a7-11e7-81eb-ec46b14648cb.png).

Solutions:
- easy: use the normal tabs under the title. And make those responsive, as on the other pages they also sometimes render broken (mobile).
- more complex: make the actual tab/title setup responsive. So flex row no break, and tabs clear under the title when there is not enough space.

In both cases, we have to find a working solution for small screens. Maybe make a dropdown (select?) or make tabs horizontally scrollable.

I think that we should go for the easiest solutions of both cases (since making cool tabs is not the priority of r4), and find a solution that works across uses cases and pages.

![screenshot from 2017-11-13 19-24-00](https://user-images.githubusercontent.com/1502484/32741952-3c7f49a0-c8a8-11e7-9007-2117f428cf44.png)

**Comment by oskarrough** [comment]
Started fixing in https://github.com/internet4000/radio4000/pull/129
