### ISSUE TITLE
add a marker on tracks that have dead youtube links

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#133]
This is a feature requested for long while by https://radio4000.com/radio-gael

That user asked to be notified when one of his track is dead, aka Youtube link no longer exists.

- step 1 (mvp): toggling a track preperty: `deadLink: true`, only on the user's own track, when the user tries to play a track they own, and the link is dead.
- step 2: every user (logged in or not) can update any `track.deadLink`. Harder to implement since we would have to change the track model rules on Firebase
- step 3: when tracks are made unique (based on their provider ID), we can offer suggestions of links that have been used by other users having the same track in their radio.

Notes:
- this notification should only be seen by the user owner of the track
- we should not offer the user to delete the track, as it is an advantage of radio4000 against Youtube's playlist, to not loose one item in a playlist when it is removed (for a reason or an other)

**Comment by oskarrough** [comment]
This would be nice. The MVP is OK but it's more interesting with a solution that doesn't require the channel owner to go through all +1k tracks manually. It will probably never ever happen.

Your step 2 is also a good idea but I don't know a good way to deal with the rules. A new model would solve that, which leads to your step 3.

I also need something similar for my TV project. For that case, I thought about something like this (not real code) that runs on firebase functions or similar. Then we have admin rights and can bybass the rules.

```js
async findDeadLinks(arrrayOfUrls) {
  const promises = arrayofUrls.map(url => {
   // parse ytid from url
    return fetch(`https://media.now.sh/youtube/${ytid}`)
  })
  await RSVP.all(promises)
}
```

**Comment by hugurp** [comment]
Maybe something backend based is safer, but will consume more time and ressources compared to a solution sharing execution on the differents users terminals.

I would prefer to have a decentralized solution, maybe a combination of both?

1. a user plays a tracks that sends the provider error code for `media no longer exists`. If this `track.invalidProviderId` (exemple) is not already set to true it goes to step 2, otherwise it does nothing
2. this user then sends the media id to an endpoint of ours `/invalid-media` (for exemple)
3. our endpoint makes a second check to the Youtube api to see if the track is really not available any longer (or if user send invalid warning)
4. if the track is invalid the endpoints toggles the `track.invalidProviderId` propterty to `true`

**Comment by oskarrough** [comment]
🎉 fixed by @hugurp in 

https://github.com/internet4000/radio4000/pull/241
https://github.com/internet4000/radio4000/pull/242
https://github.com/internet4000/radio4000/pull/243

Also see https://github.com/oskarrough/radio4000-scanner
