### ISSUE TITLE
W shortcut is still changing radios when closing a tab

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#137]
Still lthe same bug that is pretty anoying, keyboard shortcuts have to be changed.

Reproduce:
- open web browser, any
- have two tabs ope, tab 1 radio4000 with a channel playing, tab 2 any empty tab will do
- close tab 2 with browser shortcut `Ctrl-w`, and release `Ctrl` key before `w` key
- it will trigger the `w` shortcut that changes radio

**Comment by oskarrough** [comment]
Yes. Shall we move the shortcut to `R` for random? Other ideas?

People are used to `R` toggling repeat but we won't have that. If it's confusing we can also remove the shortcut until https://github.com/internet4000/radio4000/issues/87 is resolved?

**Comment by hugurp** [comment]
I think `R` is good and safe as it is also refresh page (with `ctrl`), so it does not risk to trigger anything unexpected or undesired.
