### ISSUE TITLE
Do not display @last-updated if > 12 month (to be debated)

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#138]
I think the `channel.lastUpdated` is a very good indication for users who are digging radio4000, or following some radios.

But by no means it attests of the quality of a radio channel, which does not decreases with time.

Therefore I propose that we hide the last updated indication on channels that have not been updated in a certain time, for showing by the user interface that a music selection based on one's taste is timeless.

It could be 12 month, could as well be 6, 4 or 2 month.

As a personal belief, after 2 month I do not care what is written, and the informations becomes irrelevant to me.

Opinions?

**Comment by oskarrough** [comment]
Yes. For me it could be anywhere between 1 month and 1 year, too.

> "Last updated 7 months ago"

doesn't really use it…

> "Last updated 2 months ago"

Alright not super active…

> "Last updated 1 month ago"

Probably just doing other stuff.

So, how about 1 month? 2 months?

**Comment by hugurp** [comment]
We could go for 2 month.
We also have to take care that it is not too little and loses totally its iinterest of showing that a radio has recent acticity.
