### ISSUE TITLE
`ESC` key in input/textarea should unfocus

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#146]
When an input/textarea are focused, the `ESC` key should unfocus.

Unfocus could be focusing something else, like the body.

It is very important, because some pages have input autofocus, and therefore it breaks the shortcuts workflow.

Maybe we have to reopen the input and teaxtarea class to do that.

Note: is this actually needed? actually most sites don't have this feature.

**Comment by oskarrough** [comment]
Hmmm... Good question. I also thought/think `ESC` should unfocus/blur.

But GitHub doesn't do it. Neither does iTunes or Chrome. Anyway, this is a naive solution 🗡 

http://jsbin.com/fasonif/1/edit?html,js,output

```js
document.onkeydown = function(evt) {
  evt = evt || window.event;
  // 27 is escape
  if (evt.keyCode == 27) {
    document.activeElement.blur()
  }
}
```

**Comment by oskarrough** [comment]
Come to think of it, it would be nice if our input fields did onfocus on esc. I see that GitHub added the same here in this comment textarea.

If we don't, there's no way to fully navigate Radio4000 with the keyboard. So I think we should consider how and do this.

**Comment by hugurp** [comment]
Does not seem to be working for me on Github. Would be cool, but not sure it is that easy.

**Comment by oskarrough** [comment]
just checked again, seems to be a Google Chrome feature…

**Comment by hugurp** [comment]
Let's close this as now the UX is good from that regard. (reopen if disagreeing :})
