### ISSUE TITLE
Mobile fullscreen - player controls' not visible

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#150]
When the player is fullscreen the controls are not visible, you would need to scroll the page to have them in the viewport.
![screenshot_20171122-085432](https://user-images.githubusercontent.com/1502484/33120477-731fca0e-cf72-11e7-991b-9e8ff1b28090.png)
![screenshot_20171122-085341 1](https://user-images.githubusercontent.com/1502484/33120478-734fa1ac-cf72-11e7-8cc7-7e7af2b933c2.png)

**Comment by oskarrough** [comment]
What if we remove the default/medium player size on mobile and only have mini + fullscreen? Could be complex. The default size is only a few pixels away of being fullscreen anyway so it doesn't bring anything.

**Comment by hugurp** [comment]
I think this is a good idea.
The medium page is more anoying than anything on small screens.

Just, on the screeshots above, the player is fullscreen. So it does not change anything to this bug

**Comment by oskarrough** [comment]
Right, back to this issue.

It is probably the `min-height: 100vh` + the height of the browser-url bar that makes trouble. Common trouble. Not sure what we can do. It's only on real mobile devices, correct? E.g. not the developer tools emulation.

https://developers.google.com/web/updates/2016/12/url-bar-resizing
https://gist.github.com/pburtchaell/e702f441ba9b3f76f587
https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser

**Comment by hugurp** [comment]
Seems to work on FF Android but not chrome
