### ISSUE TITLE
Get out of Google Analytics

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#155]
Google Analytics works great but is invasive.
It would be great to support a more libre alternative like https://piwik.org.

It comes with having to host it yourself, it is therefore more work.

**Comment by hugurp** [comment]
Maybe that is a temporary solution, before having our own hosting.
Maybe that is actually also require by law in some countries.

In any case , we'd better implement such a simple page.

![deepinscreenshot_select-area_20180201000403](https://user-images.githubusercontent.com/1502484/35652318-584b9e76-06e3-11e8-9a40-2a7468c857b1.png)

**Comment by hugurp** [comment]
As a temporary fix, and maybe a legal requirement we could do this solution:

![deepinscreenshot_select-area_20180201000403](https://user-images.githubusercontent.com/1502484/35652402-c3664c06-06e3-11e8-9d0b-7a423ba0f25b.png)

This would mean:
- [ ] create a new route radio4000.com/`trackers`
- [ ] write "opt out from Google Analytics" text
- [ ] add opt-out-link: https://tools.google.com/dlpage/gaoptout
- [ ] add link to go back to radio4000.com home page
- [ ] simple design inspired from https://radio4000.com/about/contact or anywhere else on the site.

**Comment by oskarrough** [comment]
Yes, I like that.

If we call the route `/terms` it could also explain the terms of service/privacy rules?

**Comment by oskarrough** [comment]
https://matomo.org/blog/2018/01/piwik-is-now-matomo/
