### ISSUE TITLE
Image refactoring in the database

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#161]
We are loading way too many images from the database.

Background. We have two models: `channel` and `image`. A channel has many images although we never use anything but the latest image from a channel. The latest is aliased with `channel.coverImage` in the Ember model.

When you upload a new image to a channel, the old images are NOT deleted. We simply always refer to the newest one. This, combined with the fact that the relationship is marked as `async`, we end up loading and processing tons of images.

Idea for a solution:

1. Run a script on the DB to remove all old images, also from the cloudinary. Or at least save them in a list so we can delete them at some point.
2. Change `hasMany` to `belongsTo`

**Comment by oskarrough** [comment]
migration script is here https://gitlab.com/internet4000/radio4000-admin-backend-express/merge_requests/1

**Comment by hugurp** [comment]
need to update the radio4000-api images docs before closing this; ref: https://github.com/internet4000/radio4000-api#endpoints

**Comment by oskarrough** [comment]
How do we know which images to delete?

```
1. Get all live images --> https://radio4000.firebaseio.com/channels.json
2. Get all images from cloudinary --> how?
3. Compare the two lists and delete every image on Cloudinary not matching one from 1)
```

**Comment by hugurp** [comment]
Let's close this and discuss cloudinary image cleaning more in details in the appropriate channel
