### ISSUE TITLE
Better search

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#163]
The search we have on `/all` only searches the data we already have in the store. It doesn't scale. We need something that scales. This would also allow us to continue with pagination.

Projects to consider

- https://lunrjs.com (interesting since no server needed)
- https://www.algolia.com/
- https://www.elastic.co/
- https://github.com/firebase/flashlight

**Comment by hugurp** [comment]
https://sizzlejs.com/

**Comment by oskarrough** [comment]
I tried out Algolia again and here's a little status report.

They have a free "community plan" with a limit to 10k records. So we can't use it for tracks but it'll work fine for radios.

Updating the search index from Firebase is pretty easy. I followed this guide https://www.algolia.com/doc/tutorials/indexing/3rd-party-service/firebase-algolia/. And we can customize the ranking with last updated, amount of tracks etc.

Some tests:

- https://www.algolia.com/realtime-search-demo/search-channels
- https://www.algolia.com/realtime-search-demo/another

**Comment by oskarrough** [comment]
Made a repo with the node script that generates the search index. Just in case :]

https://github.com/internet4000/radio4000-search-index

**Comment by oskarrough** [comment]
Search UI inspiration for better and worse.

- github header search
- https://github.com/internet4000/radio4000 (press `t` on your keyboard)
- https://support.stripe.com/search?q=money
- https://gitlab.com/search?utf8=%E2%9C%93&search=what&group_id=&project_id=&repository_ref=
- https://open.spotify.com/search/results/boogie
- https://www.algolia.com/doc/ (top right corner)

**Comment by oskarrough** [comment]
https://www.algolia.com/doc/tutorials/indexing/3rd-party-service/firebase-algolia/#ongoing-live-sync-to-algolia

**Comment by hugurp** [comment]
We need to refactor/unify/improve how search works on our app, on many routes. Anfixea few bugs that prevent some search to work correctly; quick list:
- https://github.com/internet4000/radio4000/issues/212
- #275
- #265
- #233

**Comment by hugurp** [comment]
![deepinscreenshot_select-area_20190117104258](https://user-images.githubusercontent.com/1502484/51309499-d4b15300-1a44-11e9-9850-8c2f30a711fc.png)
Fig . something not stupid, quick jump search available everywhere, first result being "go to detailed search result", and all the next results (1 + n ) are quick jumps to the project.

For r4 it could be the same
1. first result goes to a detailed search result page
2. all other results are the quick jump like implemented in #298

**Comment by hugurp** [comment]
Think we have something now that fixes this issue. Search is always something to improve, but it is a new issue now.
