### ISSUE TITLE
remove border-bottom on button 

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#171]
here:

![deepinscreenshot_select-area_20171217161113](https://user-images.githubusercontent.com/1502484/34080871-08561084-e345-11e7-8d06-7281c13f1e20.png)

I think tat we should remove it on all buttons, not only in this special case.

**Comment by oskarrough** [comment]
😢 I like that style but you're right it does create issues. Perhaps it's for another project. Let's remove them.

**Comment by oskarrough** [comment]
Removed in https://github.com/internet4000/radio4000/commit/048cb6aa6d93c61d721dac2afdb4691b08174353
