### ISSUE TITLE
should there be a repeat button on the player?

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#175]
Should there be a button that you can click, and it will repeat one track in a loop?

Now that I write this, I realize that we could have this feature almost for free in the radio4000-player, with the new features brought by the search, and the acceptation of playlist by the player.

There could be a `input` type `checkbox` at the end of the trak list (oposite to the new "query" display which is as the top), to toggle the loop of this curent selection.

could be nice UX, a little hidden, but kind of advanced too (not everyone wants to see a repeat button, or could feel confused by one more button to the UI).

**Comment by oskarrough** [comment]
I'm not against it but I don't think a repeat button is worth the trouble.

**Comment by hugurp** [comment]
no me neither.

But if I had to implement it, maybe
