### ISSUE TITLE
Player query isn't removed when switching channels

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#180]
The `service:player.query` we set and use to show when a selection is being played is not being reset when you switch channel.

The query is set when you press 'play selection' on the `channel/tracks` route. But it is not cleared. 

Maybe we can clear it here https://github.com/internet4000/radio4000/blob/master/app/services/player.js#L55.

What do we do? Alternatives?

**Comment by hugurp** [comment]
I think we should remove the `query` parameter on the `radio4000-player` element.

Here, https://github.com/internet4000/radio4000/blob/master/app/services/player.js#L126
we should pass the `query` as a parameter of the playlist we pass down, so each time the playlist changes, the `query` is passed associated with it.

**Comment by oskarrough** [comment]
@hugurp check the two above pull requests. As far as I could test it works much better with no seperate API for `query`. It's a lot easier to reason about now gj.
