### ISSUE TITLE
Write documentation about the session service

### ISSUE THREAD

**Issue by lucho1112** [internet4000/radio4000#182]
There's no docs about how to access the current user and how to access its properties.
Where should this info go? 
Who knows about it?

**Comment by oskarrough** [comment]
How about a brief paragraph or two in the readme on this repo about "Authentication"?

It could mention and clarify

- firebase auth -> emberfire -> torii -> session:service

**Comment by oskarrough** [comment]
Started writing https://github.com/internet4000/radio4000/pull/186
