### ISSUE TITLE
Meta title is not working

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#184]
When you go to a channel the meta `<title>` is no longer being set. Perhaps ember-cli-head got not requirements?

The code is here https://github.com/internet4000/radio4000/blob/master/app/channel/route.js#L34

**Comment by oskarrough** [comment]
Meta tags are now back in since https://github.com/internet4000/radio4000/commit/2f3008dd42dbebdad842064e926dff2e5c308c63.

But you still don't see the change in browser-tabs because there are two `<title>` elements. One from our index.html and another inserted-via-js from ember-cli-head. The brower ignores anything but the first.

Two ideas:

- remove <title> in index.html (not nice since no title outside of js)
- integrate option in ember-cli-head to replace current title tag instead of creating a new one

**Comment by hugurp** [comment]
option 2 seems to be the best

**Comment by oskarrough** [comment]
Issue is at github.com/ronco/ember-cli-head/issues/36 (not linked so github doesn't link our issues)

**Comment by oskarrough** [comment]
Related idea: add current track when it's playing. Needs to be clarified.

**Comment by hugurp** [comment]
I see two sides to this story:

- SEO titles
-- each page should have a different title, "About - Radio4000", "200ok - Radio4000"

- human users titles, when the player is on
--1. either each title stay the same
--2. either the title is "current artist -current track" in playback
--3. or solution 2. But only when the tab is not active

Thoughts?

**Comment by oskarrough** [comment]
Yea not sure how to deal with it. It gets confusing when the title wants to both show which page you're on but also what's currently playing.

You could argue that showing what is currently playing is more important than exactly which route you're actually on.
