### ISSUE TITLE
Add missing `create your radio` button on homepage (when logged out)

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#191]
We don't explain to logged out users that they can, not only listen to existing radios, but create their.

One way it is good, so only people who really want to join will make the effort to connect and create their radio.

But we never explain that there is a possibility, except in the about page.

Maybe just adding a `create your radio` button with the two other buttons would be enough.
Button that is a link to sign up.

Therefore, we maybe have to improve the signup page with some explicative text, "why you would sign up", to create a radio and so on.

**Comment by oskarrough** [comment]
Here's a quick test. This is how it looks now: https://master--radio4000.netlify.com/auth/signup

Tried two changes:

1. Rename 'sign up' in menu 'sign up / create radio' (this works because signup redirects you to create a new radio after signing up)
2. Add some more explaining text on /signup and tweak it

<img width="1040" alt="screen shot 2018-01-19 at 19 25 36" src="https://user-images.githubusercontent.com/184567/35165689-97f37528-fd4f-11e7-9958-58ba30a7bb27.png">

While it's not super exciting it is little improvement. That being said I hope we'll come up with something better ✌️  Ideas?

**Comment by lucho1112** [comment]
Why not being even more "radical" and just go for "create radio" (give up the "sign up" text)? I am more talking about the menu part, but this could also have consequences about the wording on the sign up page.

I think it's beneficial in multiple ways: 
- As you said @oskarrough , anyway the "sign up" button leads the user to create a radio in the end. So for radio4000, "sign up" = "create radio". Why using too many words for what will be in the end the same action? I feel keeping only "create radio" is more straightforward, explains more clearly what is the aim of this action.
- Following this idea, it would be quite clear for the new user from the beginning that this action will lead him/her to be part of this community of radios. It deletes a potential ambiguity that, by "signing up", he/she would only be a "privileged observer" that could maybe only have some radios in its list of "favorites"
- This would also be a way to differentiate radio4000 from any other web service you can think of. For a new user, "Create radio" is a more original and interesting action than just "signing up" to a website.

**Comment by oskarrough** [comment]
I really enjoy this direction. It will allow us to focus on 'creating a radio' rather than 'signing up'. Signing up is more of a techincal bother and not a goal by itself anyway.

**Comment by hugurp** [comment]
I enjoy your additions @oskarrough .

No strong argument against `Sign up` replaced by `Create radio` come to mind, and the advantages definitely exist.

The `Sign up` button is there in a very classical sense, as I enjoy staying as close as possible between the acitons's universal meaning than its specificity.
I think we need to remember that a lot of users will also not want to learn to our specific wording (at first use), in this case search for the specific action to `register/sign-up` and benefit from whatever possibility this software has to offer.

**Comment by lucho1112** [comment]
Is it that specific for a new user @hugurp ?
As you said, it is indeed **for us** a specific wording. But for a new user, more than being specific, a button with only `create radio` is quite logical:
- He/she lands on an environment where it becomes quite obvious that the "content" of the website consists in hosted radio. Moreover, the aim of the website is explained from the homepage, the new user can play some radio before any registration and, if even more curious, can read the about page.

My opinion is: we can then assume that, being exposed to all of this, the new user will understand quite clearly the specificity of a `create radio`button. It looks quite self-explanatory to me considering the environment the new user is being exposed to beforehand.

I kind of see it as a good opportunity of being able to kill two birds with one stone. It's an 'easy win' in the way that it somehow shows the singularity/specificity of the radio4000 service without losing the new user into something he/she wouldn't understand.
