### ISSUE TITLE
channel-header > <img> has an error in its title attribute

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#202]
Gotta investigate from here: https://github.com/internet4000/radio4000/blob/master/app/components/channel-header/template.hbs#L10

![deepinscreenshot_select-area_20180204004649](https://user-images.githubusercontent.com/1502484/35772803-c1f5aa0c-0944-11e8-81fc-c5f3f300b780.png)

**Comment by oskarrough** [comment]
The `alt=""` attribute is missing/wrong.
