### ISSUE TITLE
Add tag list and select tags on /channelSlug/tracks

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#207]
For exemple: 

![deepinscreenshot_navigator_20180222111359](https://user-images.githubusercontent.com/1502484/36532529-3bcc364a-17c1-11e8-849c-c4a73927f1ad.png)

- User tags: the ones the user themselves ad din their `track.descriptions`
- Generated tags: the one sgenerated from related links, ex: Discogs

**Comment by oskarrough** [comment]
Done in https://github.com/internet4000/radio4000/pull/405
