### ISSUE TITLE
Add support for Discogs release link in `/add` form

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#208]
![deepinscreenshot_select-area_20180222113514](https://user-images.githubusercontent.com/1502484/36533563-33ae14a8-17c4-11e8-87df-64b13ec91ea3.png)

The same way the Youtube link is used to fetch their API for a track title, the Dicogs link will be used to fetch related aditional data (from the release id).

This features goes in hand with **radio4000-api** changes discussed here: https://github.com/internet4000/radio4000-api/issues/36

Created the following regex (I am sure it can be improved and simplified) to get the **Discgos release id** from its URL: `/([0-9]+(?:$|(?=\?)|(?=\/$)))/gm`
Tests interface here: https://regexr.com/3i5fa

Documentation: https://www.discogs.com/developers/

Data fetched with the Discogs api should be the following, of the `master release`:
All the data is listed here (https://www.discogs.com/developers/#page:database,header:database-release — have to toggle the 200 ok response), here listed in general terms:
- release year
- release label
- release genre and style
- release artist

Ex release page: https://www.discogs.com/Nu-Guinea-The-Tony-Allen-Experiments/release/7983975

**Comment by oskarrough** [comment]
Done in https://github.com/internet4000/radio4000/pull/273
