### ISSUE TITLE
no redirect after login

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#21]
If you go to the login page, login a first time it will redirect you to your channel (as it is supposed to be).
But if you logout and then login a second time (not necessarily to the same account), it won't redirect you to your channel, and will not actually visually log you in.
If you then refresh the page, you will be logged in.

**Comment by hugurp** [comment]
as described by sam

**Comment by oskarrough** [comment]
It should redirect to your channel, right?

**Comment by hugurp** [comment]
I'd say so too

**Comment by oskarrough** [comment]
Fixed in master
