### ISSUE TITLE
Add shortcut to focus search

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#212]
`s`, when on should be the shortcut to focus the search input.

on:
 
- radio4000.com/all
- radio4000.com/acapulco

Note:
Of we ever implement Algolia's search on `/all` or on a more global route, the `s` shortcut feature could target this the new algolia search input. Question then araises when on a `/$channel{/,tracks}` route, which input (if there are two, one global and one for this channel tracks) does `s` focuses? Maybe we can answer later to this.

**Comment by oskarrough** [comment]
You mean instead of `shift+s` like now?

If we get a global, channel search we could split it:

- `s` = primary, global search (channels)
- `shift+s` = secondary, contextual search (tracks)

Another note: it's a bit confusing that `g+s` takes you to favorites and not /search.

**Comment by hugurp** [comment]
But there is no `/search`?

`g + s` = go starred, aka the channels you added a star to favorite.

Totally forgot about the `S` shortcut (shift + s). Also we should therefore add it to `/all` where it is not implemented.

**Comment by oskarrough** [comment]
There is search here https://radio4000.com/search. But perhaps this is an indication that it should be renamed again.

**Comment by oskarrough** [comment]
> Totally forgot about the S shortcut (shift + s). Also we should therefore add it to /all where it is not implemented.

Yea, let's do that? I just remembered that we moved it from `s` to `shift+s` to avoid a conflict with the shuffle shortcut.

https://github.com/internet4000/radio4000/commit/e5cd988f3584fc5356fddb5b086a11a0d0d1dd39

**Comment by oskarrough** [comment]
Or forward slash `/` like on github.com and vim.

**Comment by hugurp** [comment]
I think we could start by adding the *focus search* `shift + s `(S) feature like on the /tracks page, to:
- /search 
- /channel-slug/favorites (#265 )

**Comment by oskarrough** [comment]
so when you're on one of those pages, `shift+s` focuses the search input? go for it!

**Comment by oskarrough** [comment]
This can be closed now? You focus search with `/` forward slash /cc @hugurp

**Comment by hugurp** [comment]
no the same thing,`/` focus the quick jump, not the search input on `/explore`

**Comment by oskarrough** [comment]
Ah ok! So how to proceed…

Should we add `shift + s` for the "contextual search"? Another keybind?
For instance on /explore or /followers (once we get search there, too).
