### ISSUE TITLE
Change styles of channelCard's channel.body tags to bold (instead of underline)

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#214]
To make it more consistent and visually appreciable let's change the css styles of a channel's tags, when displayed on `/$channel`.

On Radio4000 https://radio4000.com/200ok the tags are underline, when on the homepage, in the **channel-card** component, the channel body tags are displayed in bold.

![deepinscreenshot_20180402120320](https://user-images.githubusercontent.com/1502484/38192475-5e2b2d84-366d-11e8-9821-5eb766fec86b.png)
Fig 1. the two component that need to be harmonized in their `url` context

# what to investigate

- [ ] how to better target the tags of a channel's body with css; class naming convention, coherence with how it is implemented with `channel-card` component
- [ ] put the styles in the right file inside `radio4000/app/styles`

**Comment by oskarrough** [comment]
Cool! You can consider keeping links in the text color `#4d4d4d`. Might be too much with bold AND darker color? Just a thought.

**Comment by hugurp** [comment]
done in previous release

**Comment by hugurp** [comment]
done in previous release
