### ISSUE TITLE
Login with Google error when multiple Google accounts are used in Browser 

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#216]
Originally opened by @tristanballe1, in https://github.com/internet4000/radio4000-api/issues/41.

> Gentlemen,
Because I am using several Gmail accounts at the same time, I cannot log-in to R4000 using gmail, the pop up triggered keeps running and nothing happen (see the attached file)
Therefore, the solution is to log-out from all the google accounts and only keep the one I registered to R4000 with... It's doable but not that convinient.
Peace !

![38427002-5f176412-39b8-11e8-9e8d-ee5e3c542951](https://user-images.githubusercontent.com/1502484/38429076-b1340a84-39bd-11e8-805a-81c5a78555dc.png)

**Comment by oskarrough** [comment]
If you 

1. open the popup to connect with Google or FB
2. close it without selecting an account

an `auth/cancelled-popup-request` error is fired. This error prevents the popup to open again. I think this issue can be solved by NOT throwing on that error here https://github.com/internet4000/radio4000/blob/master/app/auth/settings/account/controller.js#L52

**Comment by oskarrough** [comment]
OR, maybe it's the browser somehow canceling the popup? We can look into using redirect instead. Redirect is prefered on mobile anyway.

**Comment by hugurp** [comment]
Let's say that you should not use google anyways to login?

I guess I don't feel like spending time improving Google login UX atm. Reopen if more complains maybe.
