### ISSUE TITLE
Improve image quality

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#217]
We've been tweaking the parameters for image quality on the channel cards to improve performance several times. But I think it could use another go. The current image quality makes it look bad.

Here some examples. Will need more tests with different images, gifs, text-based, pictures. Since the `q_auto` optimizes depending on your connection, that might be a good choice. Also sharpen filter is useful. In the end, I don't think we need to improve the quality by much to make it feel a lot better and it's also not urgent.

(edit, below includes .webp examples so use chrome :()

quality 50, 2.5kb (current)
![](https://res.cloudinary.com/radio4000/image/upload/w_200,h_200,q_50,c_thumb,fl_awebp/l3bv5emgwnfbgsvvv7oa.webp)

q50 + sharpen, 3.4kb
![](https://res.cloudinary.com/radio4000/image/upload/w_200,h_200,q_50,c_thumb,fl_awebp,e_sharpen:60/l3bv5emgwnfbgsvvv7oa.webp)

automatic quality, 3.7kb
![](https://res.cloudinary.com/radio4000/image/upload/w_200,h_200,q_auto,c_thumb,fl_awebp/l3bv5emgwnfbgsvvv7oa.webp)

no quality set, 3.6kb
![](https://res.cloudinary.com/radio4000/image/upload/w_200,h_200,c_thumb,fl_awebp/l3bv5emgwnfbgsvvv7oa.webp)

The sharpen filter also makes a difference:

q_50, no sharpen
![](https://res.cloudinary.com/radio4000/image/upload/w_200,h_200,q_50,c_thumb,fl_awebp,e_sharpen:60/zr7ux38dwusgdcjfzb2y.webp)

q_50, sharpen
![](https://res.cloudinary.com/radio4000/image/upload/w_200,h_200,q_50,c_thumb,fl_awebp,e_sharpen:60/zr7ux38dwusgdcjfzb2y.webp)

q_auto, no sharpen
![](https://res.cloudinary.com/radio4000/image/upload/w_200,h_200,q_auto,c_thumb,fl_awebp,e_sharpen:60/zr7ux38dwusgdcjfzb2y.webp)

q_auto, sharpen:60
![](https://res.cloudinary.com/radio4000/image/upload/w_200,h_200,q_auto,c_thumb,fl_awebp,e_sharpen:60/bx9iaq4435wngpkm7ni5.webp)

**Comment by hugurp** [comment]
I'd say, let's not alter / edit / sharpen images. Let's take a format that works on every terminals, even though the file size could be a bit higher
