### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nunojesus** [internet4000/radio4000#221]
Hi I read your work and I love this project, so If you want I can make you a new logo for this project.

Greetings 

Nuno

**Comment by oskarrough** [comment]
Hey Nuno, that's a very kind offer, thank you and glad you like it!

But we're actually pretty satisfied with the current logo for the project… You can find the files here https://github.com/internet4000/assets/tree/master/radio4000.

**Comment by nunojesus** [comment]
No problem if you need something, Im here to help!
Greetings

Nuno
