### ISSUE TITLE
/add?url= is broken

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#222]
the url https://radio4000.com/add?url=https://www.youtube.com/watch?v=XmhZS4hr2gU should load the add track form with the specified youtube url

Right now it does not, and loads https://www.youtube.com/watch?v only. Somehow all the part `=XmhZS4hr2gU` is removed.

Is this something that has to be fixed in r4?

https://github.com/internet4000/radio4000/blob/master/app/add/controller.js#L8

On https://radio4000.com/add?url=https://www.youtube.com/watch?v=XmhZS4hr2gU ,
`var u = new URL(window.location)` gives a correct object with `u.search` = `'?url=https://www.youtube.com/watch?v=XmhZS4hr2gU'`.

So somehow it seems to come from r4, but I do not see where.

**Comment by oskarrough** [comment]
Observation: on google and duckduckgo the query `a=b` is accepted. Duckduckgo encodes it as well, google leaves as is.

Very related https://discuss.emberjs.com/t/ember-query-params-ignoring-character/12188/
