### ISSUE TITLE
Make `g t` shortcut contextual

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#257]
Ref: https://github.com/internet4000/radio4000/issues/213

The shortcut used to "go to tracks", `g t`, should go to the *current channel loaded on the route's tracks*.

Right now it is going to the logged-in user channel's tracks page.

Maybe if the current route is not a channel route it should go to the tracks route of either:
- the current channel being played (i'd say so)
- the logged in user

So then:
- if the user would like to go their tracks page, `g i` + `g t` would work
- in case the user wants to go to the current channel tracks `g c` + `g t` would bring them there

**Comment by oskarrough** [comment]
Sounds good.

So when you press `gt` we find the channel from here, in priority:

1. use `channel` route (or any child route of that)
2. use `player.currentChannel`
3. use `session.currentUser` channel

**Comment by hugurp** [comment]
This has been done, gg
