### ISSUE TITLE
Broken channel header

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#263]
We should fix the new image size to work with the channel header.

Any suggestion, or do we just do it like it was?

![deepinscreenshot_select-area_20181018163348](https://user-images.githubusercontent.com/1502484/47162462-4b2e9f80-d2f4-11e8-94d1-0197a2e3baf2.png)

**Comment by oskarrough** [comment]
Check https://github.com/internet4000/radio4000/pull/264

**Comment by oskarrough** [comment]
Here's a little design brief and overview of what we currently show. Not that our imagination should stop there!!

- square cover image
- title (Radio Oskar)
- slug ("@oskarrough")
- description (can contain clickable hashtags, max 300 chars)
- website link (just one)
- updated (3 days ago)
- map link
- [ listen/play button -> play another button]
- [ favorite/remove favorite button ]
- recent tracks
- share this radio (currently at the bottom, an url or embed code)

It needs to work at 320px (mobile) and 620px (our current max width on desktop).

**Comment by hugurp** [comment]
Closed by https://github.com/internet4000/radio4000/pull/266
