### ISSUE TITLE
Map query params cluttle the browser history

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#271]
The map query parameters, `lat`, `lng` and `zoom` are changing each time the user moves the map.

So if you go the map, and move the map for a few seconds, you cannot use the back button anymore. This because there are many browser history entries that have been added with all the locations of the map you "zoomed in and moved to".

To try it out, go to a homepage of a radio channel that has a position on the map, then click its `map` link, to reach its position on the map.
Now navigate a bit on the map, exploring it for a minute.
After this, try to reach the original radio homepage (where you started), using the browser `previous page` (back in history) button.

**Comment by hellerve** [comment]
You could try replacing the history instead of adding to it!
