### ISSUE TITLE
Broken search on channels

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#274]
on https://radio4000.com/search the search no longer works

to reproduce,
- open https://radio4000.com/about
- click on `radios` in the side bar
- click `search` to end up on all radio pages
- search for a particular radio, that should not work

maybe try that refreshing a few times

I haven't investigated further.

Maybe we fix this, maybe we implement algolia already.

**Comment by oskarrough** [comment]
If we go the Algolia way, there's https://github.com/internet4000/radio4000/issues/163.

**Comment by hugurp** [comment]
seems it is working now
