### ISSUE TITLE
Can't send feedback

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#278]
When you try to send feedback via https://radio4000.com/feedback I get an error in the console:

> Access to XMLHttpRequest at 'https://script.google.com/macros/s/AKfycbxhHhA5ppmIJXZA41ehfZjtSeyDFa_MTTjOOQ9avi-EUGB49v_3/exec' from origin 'https://radio4000.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> vendor-dea6828b246411ee858aa8018b7881aa.js:518 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://script.google.com/macros/s/AKfycbxhHhA5ppmIJXZA41ehfZjtSeyDFa_MTTjOOQ9avi-EUGB49v_3/exec with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by hugurp** [comment]
dayum

**Comment by oskarrough** [comment]
We can use Netlify headers to avoid the CORS error. Maybe it is a one-liner:

https://www.netlify.com/docs/redirects/#rewrites-and-proxying (proxying paragraph)

something like

```
/feedback-endpoint/*  https://script.google.com/macros/s/AKfycbxhHhA5ppmIJXZA41ehfZjtSeyDFa_MTTjOOQ9avi-EUGB49v_3/exec/:splat  200
```

Other ideas?

**Comment by oskarrough** [comment]
airtable?
netlify form?
fix google?

**Comment by hugurp** [comment]
idk, it was working fine until now. What happened?
