### ISSUE TITLE
Search right after add does not work

### ISSUE THREAD

**Issue by hellerve** [internet4000/radio4000#286]
When I add a track and then search for it right away, it does not work. It can be seen in the list of tracks, but not searched for. I made a GIF to highlight the problem.

![bug](https://user-images.githubusercontent.com/7725188/50052228-43874d80-0121-11e9-814c-cd2ae13e1a8f.gif)

Cheers

**Comment by hellerve** [comment]
Whoops, duplicate of #275. SOrry about that!

**Comment by oskarrough** [comment]
Thanks though!
