### ISSUE TITLE
Verify channel.slug when editing

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#33]
When creating a new radio we verify the `slug` to avoid duplicates and suffix a random string, if necessary.

On `channel.edit` we have similar logic but here it is currently broken. We should refactor and reuse the code from `channel.new` somehow.

**Comment by hugurp** [comment]
Can that be closed @oskarrough ?

**Comment by oskarrough** [comment]
No not yet. Try changing your slug to an existing one when you edit your channel. The checks are broken there right now.
