### ISSUE TITLE
Contextual toggle is broken

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#331]
On mobile it is too large and track cannot be clicked properly.

![deepinscreenshot_select-area_20190225161621](https://user-images.githubusercontent.com/1502484/53347131-c1818500-3918-11e9-8e32-51faca2893d8.png)

**Comment by oskarrough** [comment]
quickfix?

```
.Track-contextual {
	overflow: hidden;
	position: relative;
}
```

**Comment by hugurp** [comment]
seems legit

**Comment by hugurp** [comment]
fixed
