### ISSUE TITLE
Improve form validation on add track

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#335]
After adding a track, the form is cleared and again validated, which turns into this annoying message.

<img width="683" alt="Screenshot 2019-05-18 at 10 08 27" src="https://user-images.githubusercontent.com/184567/57966634-0a177000-7955-11e9-873c-3384037dbabb.png">

It should only appear if you try to submit and the field is empty. Not before.

**Comment by hugurp** [comment]
Yes good idea! Heard a few complains already, user thinking their track was not added.
