### ISSUE TITLE
Searching on `/explore` breaks profile hamburger menu

### ISSUE THREAD

**Issue by hellerve** [internet4000/radio4000#342]
Okay, so this is a weird one. Steps to reproduce:

- Go to https://radio4000.com/explore.
- Verify that the hamburger menu opens fine.
- Type one character.
- Repeat step 2.
- By the second or third character, the hamburger menu doesn’t open properly anymore.

Funnily enough, removing the search query fixes it. I really have no idea what could be going on there.

Assigned to @oskarrough as per request by @hugurp (I think he was joking but I don’t like to have fun).

Cheers

**Comment by oskarrough** [comment]
haha, this is funky bug! Appreciate it. I'll fix and report what it is…
