### ISSUE TITLE
Can't log in with Facebook on iOS

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#345]
Tested on some iPhone, when I try to log in with facebook it…

1. opens a popup
2. i sign in with facebook
3. popup closes and r4 appears again, now it's stuck at "warming transistors"

didn't try to check for errors in the console yet using some kind of remote debug stuff.

**Comment by hugurp** [comment]
arfff

**Comment by oskarrough** [comment]
Found an error in the console:

> DEBUG: Login error is not referenced: Error: The popup has been closed by the user before finalizing the operation.

**Comment by oskarrough** [comment]
OK, it is fixed if we switch to "redirect" instead of the default "popup", as we currently use. This has the disadvantage of having to reboot the whole ember app.

So I'd prefer if we keep popup where we can, and only enable redirect for iOS maybe? Or?

**Comment by oskarrough** [comment]
To switch, we add `redirect: true` here https://github.com/internet4000/radio4000/blob/7191eec7fb7aa5caf301657c303a72d2b3b06ed8/app/auth/route.js#L37-L43
