### ISSUE TITLE
Add no-javascript warning/graceful fallback

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#36]
Maybe with a link to the github repo with a line explaining code can be reviewed and reused.

No sure what could be a more graceful fallback, since we would need javascript to make a playlist of all videos and play them one after another.

Ideas?

**Comment by oskarrough** [comment]
I just know see that our current `<noscript>` fallback is covered by the absolute "dummy app" on top.

https://github.com/internet4000/radio4000/blob/master/app/index.html#L23
