### ISSUE TITLE
Remove "My Radio" from the menu

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#408]
when you're signed in with a channel there are two links to your channel in the menu. How about we remove the "My radio" one? E.g. only keep the card.

![image](https://user-images.githubusercontent.com/184567/65793773-e962f080-e166-11e9-914f-c127e8787fec.png)

(screen of current menu)

**Comment by hugurp** [comment]
Ja, maybe makes sense. I think it was added because users get confused that the "my radio"link is a different form/shape than the rest of the menu items
