### ISSUE TITLE
Should we merge in the discogs-explorer routes

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#409]
This prototype project https://github.com/internet4000/explorer-discogs has been an experiment for exploring Discogs data; adding the possibility of a player that can continue playing the videos of a release across application routes. This is neat when exploring labels, artists.

One "annoying thing" about this project, is that we've got work again on UI, integrating the player and visual components etc. This job could be simplified if we reused the components of radio4000 ember's app (which both of them are).

The idea here, is to reuse the "glue" logic, such as adapters and serializers, routes and controllers from discogs-explorer, and merge it into radio4000-cms.

# What would this bring?

- possibility to explore the publicly available discogs catalog with a nice UX (our job)
- start a better linking of meta-data withing r4; Discogs is first step, but we can also have other providers (musicbrainz, imdb (?!?!yah eh)).

# Alternative solutions

We can also keep this as two separate applications, and work on a "design framework" we could reuse in multiple apps. This feels tedious, we're not google material ui.

We could move to a design framework (meh, no thx).

If we'd like a great integration with the "r4 ecosystem", it is necessary to be able to authenticate users so managing one's r4 library within external apps is possible (adding discogs/provider URL to a track, new track etc.)

# Challenges

- need to have a solid ed-api. Aka, we can handle request load and have as much uptime as r4 has had. Probably our dear cloud provider can provide $4service
- maybe work on a server with discogs db self-hosted (they offer that, but that is a whole little project to itself)

# What we already have

- nice player than can play from playlists, and multiple providers (discogs offers youtube videos only. Maybe if r4-player is more mature we could help @discogs integrate it?)
- UI system than can handle many cases, and integrated responsive player ^

# Where to start

- what should this app's MVP do. Maybe what is already existing, integrated in r4?
- define on which route we'd like UX wise to have the logic for discogs explorer
- click all the buttons to we feel how an integration into the "r4 flow" is most agradable

**Comment by hugurp** [comment]
nope, too complex for now

**Comment by oskarrough** [comment]
Well written issue and sorry for the lack of feedback but I agree with your latest comment :D
