### ISSUE TITLE
cannot add track on mobile while playing

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#413]
![Screenshot_20191012-105911](https://user-images.githubusercontent.com/1502484/66698642-e415b200-ecdf-11e9-8c55-d54de97d157e.png)

The add button is hidden by the player. Wat to do?!

**Comment by oskarrough** [comment]
Use the overlay man ;)

**Comment by hugurp** [comment]
Good tips! ;]

**Comment by hugurp** [comment]
closed by #454
