### ISSUE TITLE
new track form `description` should be text-area

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#54]
it is an input at the moment, a text area would be better

**Comment by oskarrough** [comment]
That means we'll support multi-line descriptions? 🐙

**Comment by hugurp** [comment]
I think it would be cool, but wait for design issues...
We should maybe have first the re-UX of channel detail page?
Then we can have multiline there on channel/info.

I think multiline is complicated.

**Comment by oskarrough** [comment]
Think so too. But why make it a textarea if there's no multi-line?

**Comment by hugurp** [comment]
I think it is just more praktish to see the full text you're editing, instead of having to scroll horizontally.

The problem with multi-line is that we somehow need to manage two versions of the text:
- one for when we want multi-line
- one for when we don't want it

Let's not do multi-line for now, as it won't really bring anything. But we can do it sometimes we have time and motivation.

**Comment by oskarrough** [comment]
OK. So what would happen when I enter:

```
Hey sweet track.

yes it's nice

#rock #pop
```

how do we render it?

`Hey sweet track.yes it's nice#rock #pop` (trimmed)
`Hey sweet track. yes it's nice #rock #pop` (trim+extra spaces)
