### ISSUE TITLE
add `scroll to top` on routes that need it

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#61]
Changing route, in some case, should scroll to the top of the page.
This is usually a normal behavior, but SPA do not work like that.

We should identify those routes and implement a scroll top helper.

**Comment by oskarrough** [comment]
Yes. This is the common solution https://github.com/dollarshaveclub/ember-router-scroll. But let's see if we need it.

If I go to a channel, scroll down the track list, go somewhere, go back to the same channel. Should scroll position be preserved here?

**Comment by hugurp** [comment]
Scroll position cannot be rightfully preserved.
You go to /intro scroll to middle go to /all, scroll position will be preserved, but it dos not mean anything.
Same if you go to /tracks, scroll a bit, go to /settings, we won't be at the top of the route, and it won't mean anything.

I think in the majority of cases changing route should scroll to top.

Exceptions:
- overlays
-- /track/edit (not yet implemented)
-- /add

**Comment by oskarrough** [comment]
What do you mean it does not mean anything?

As an example: if I go to the "Commits" page here on GitHub, scroll all the way down, go browser history back and forth, it will preserve my scroll position and I will still be at the bottom of the commits. This would be handy for the /all and /channel routes at least.
