### ISSUE TITLE
Add title text on radio / tracks filters

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#68]
On the filter buttons there are no `title`.

`<button title="">`

![deepinscreenshot_select-area_20170823205556](https://user-images.githubusercontent.com/1502484/29633099-73666eb0-8845-11e7-9b69-5ef2d7b6d71a.png)

**Comment by oskarrough** [comment]
Also the default filter should be marked as active.

**Comment by hugurp** [comment]
can that be done with something else than query params?

**Comment by oskarrough** [comment]
we can hardcode .active/is-active or whatever we use. we just have to remember to keep it sync but that could be ok!

**Comment by hugurp** [comment]
the component for filters are already complicated to use, and realy hard to reuse.
I would like to look at it see how to make it more easility reusable
