### ISSUE TITLE
Deleting channels creates orphans records

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#70]
When a user decides to delete their channel, it creates orphan records of two types:
- channel, in other user's channel.favoriteChannels
- tracks, all tracks from the now deleted channels have not been deleted

There is therefore some errors when loading a channel that has favorite that do no longer not exist

**Comment by oskarrough** [comment]
We do remove the channel everywhere it is favorited here https://github.com/internet4000/radio4000/blob/master/app/channel/delete/controller.js#L45

But tracks we don't touch… I think we should also remove them. Without a channel they're useless. Thoughts?

**Comment by hugurp** [comment]
Maybe it is better to do a firebase function that:
- deletes all tracks
- removes all relationships from channel.favorites & channel.followers
- deletes the radio channel

**Comment by oskarrough** [comment]
Related

https://github.com/internet4000/radio4000/issues/320
https://github.com/internet4000/radio4000/issues/321

**Comment by oskarrough** [comment]
So a couple of findings..

```
await $E.get('model.favoriteChannels')
```


Returns a rejected `DS.PromiseManyArray` with the reason "Record not found".

However, you can still inspect something with 

```
x = $E.get('model.favoriteChannels')
x.content.length // amount of favorites, including the deleted ones
x.content.currentState // array of something like a model
```

When you iterate through the `currentState` array, the deleted channels will have an `id` but no `title`.
