### ISSUE TITLE
rule error while saving edit on a track, just after adding it for the first time

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#82]
If you add a new track, then straight away edit it there will be a firebase rule error at save time.

Delete the track after just adding it works though, it is only edit.

If you cancel instead of saving, it works (but slow), and if you edit again a second time (without refreshing) it will work. It is only after first add.

**Comment by SamuelRott** [comment]
I can not reproduce the bug.

**Comment by hugurp** [comment]
To reproduce you need to be on the channel or channel/tracks route when adding.

**Comment by oskarrough** [comment]
I also couldn't reproduce. What to do? I tried…

1. visit /channel/tracks
2. click "add track" in sidebar menu
3. edit the new track (change title)
4. save

**Comment by hugurp** [comment]
wat the hell, am I only opening issues that are only happening to me? And which in the end don't occur any more? Closing because I don't have this bug no moar
