### ISSUE TITLE
rule error, channel title length is not the same in front end and firebase

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#83]
- at channel creation
- at channel edit save

no error are logged

**Comment by oskarrough** [comment]
They are still not synced.

- Rules say `> 2 && < 32`
- Frontend says `> 3 && < 33`

If Radio4000 is a tool, let's not dictate (too much) how you're able to name your radio. What about

`length > 2 && length < 100`?

**Comment by hugurp** [comment]
Why 100? Really? Then 1000, it's as much arbitrary.
Is this change going to help solve any problem?
Has anyone complained about the title restriction, or us encountered any problem?

But if you want and you're ready to face the upcoming issues of "really long" title, go for it.
I see this restriction as non invasive for users and life easierer for us.

**Comment by oskarrough** [comment]
I think ~30 is too restrictive. I'm sure some, not many, will annoyed when they can't name their radio like they want. With 100 I don't think we offend anyone and we still have a limit.

**Comment by oskarrough** [comment]
Fixed in https://github.com/internet4000/radio4000-api/commit/93b893e2204340a64c45c857f86b62eec1ddbd5b
