### ISSUE TITLE
Keyboard shortcuts (with radio4000-player)

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#87]
Shortcuts have to be re-implemented because they broke when we externalized the player on radio4000.com to a vue.js app to use it as npm module, web-component and iframe.

Figure out the best way to handle **shortcuts** across the two apps on the site, ember and player-vue.

Shortcuts can also be good to restructure some part of the apps in functions, making the general api clearer.

See post below for summary

**Comment by oskarrough** [comment]
Related https://github.com/internet4000/radio4000-player/issues/28#issuecomment-316069796

**Comment by hugurp** [comment]
Edit here to reflect the current decisions:

# Shortcuts

Ideas on what to do with shortcuts in r4 & r4-player

## Needed
- `p` play/plause toggle
- `n` next track
- `m` mute toggle
- `s` shuffle toggle

## other
- `l` locate track in player
- `N` previous track

## shortcuts in radio4000, not in player
- `r` random radio
- `f` go through view modes
- `F` full screen
- `?` open support site

## radio4000 naviation
- `g + r` = go to radios page
- `g + m` = go to my radio
- `g + c` = go to current radio played in player
- `g + f` = go to my favorites radios
- `g + h` = go to my history
- `g + ?` go to feedback

## advanced
- `:` open command bar
- `/` open  search

**Comment by oskarrough** [comment]
Very nice. Some thoughts:

- `p` for playback is ok. But the more I think about it the more I prefer having `space` do it and overwrite scroll behaviour since that's what I want 95% of the time
- `?` should open a panel with keyboard shortcuts inline. Try here on GitHub or on https://music.google.com
- ` /` for application-level search is super cool
- How about `ctrl/cmd`+`left/right` for previous next track? or `j/k` ala github/gmail/vim/more?
- `l` will be very handy - but should perhaps be a "go-to shortcut instead" so `g + l`
` `r` for playing something random is good unless we one day implement `repeat`

**Comment by oskarrough** [comment]
Also we have to consider, as you already did, which shortcuts go to the player and which to Radio4000. When do we accept shortcuts in the player? Always? When it has focus? Enabled by default? Setting to disable?

We can either solve that or start by implementing the shortcuts only in Radio4000.

**Comment by hugurp** [comment]
`space` in web browsers is used to scroll the screen down, `shift + space` to scroll it up.
`p` could go for play/pause.
Ofc we can break this behavior.

I don't think we should touch `ctrl` `alt` `cmd` as their are most possibly bound to user defined shortcuts and browser defaults.

`j/k`, ok, but wat for? next track? nope, j k rings the bell to vim nerds, and makes no sense. `n` sounds like next.

It might be better to start implementing them in r4 only, otherwise it could break side on which the player is embed.

But what if we implement shortcuts related to the player in the player, and have a `shortcuts=true` prop on the player?

Can iframe intercept key shortcuts when embed on a webpage?
