### ISSUE TITLE
Refactor player state

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#95]
I got a bit confused when I looked at how we currently manage the state revolving around the actual playback on R4. I'd like to discuss and hopefully make it clear what we have where. Naming is one question but we also seem have some duplicate/redundant things. Everything "works" so this can be looked at whenever we want :)

Here's an overview. 

```js
// models/track.js
playedInCurrentPlayer: false
liveInCurrentPlayer: false
finishedInCurrentPlayer: false

// models/channel.js
isInPlayer: false

// service/player.js
originTrack: null
currentTrack: null
currentChannel: computed.alias('currentTrack.channel')
isPlaying: computed.bool('currentTrack')

// components/x-playback
channel: computed.alias('player.currentChannel'),
track: computed.alias('player.originTrack'),
```

And then we have a few important methods and what vars they currently modify:

```js
visit `channel.tracks.track.index` route => player.playTrack
player.playTrack(track) => player.originTrack = track

// radio4000-player emits two events which are caught in service/player.js
onTrackChanged() =>
  player.currentTrack
  previousTrack.liveInCurrentPlayer
  track.playedInCurrentPlayer
  track.liveInCurrentPlayer
  channel.isInPlayer

onTrackEnded()  => track.finishedInCurrentPlayer
```

**Idea 1**: Remove the duplicate `player.originTrack` and keep `player.currentTrack`. Why do we have two different? Perhaps I forgot something obvious.

**Idea 2:** Instead of keeping track of what is in the player on every track and channel, why don't we store it in the `player` service only? So to find which track is loaded, we have `player.currentTrack` and to find which channel, it is `player.currentTrack.channel`.

Then we can remove these:

- `player.currentChannel`
- `track.liveInCurrentPlayer`
- `channel.isInPlayer`
- `{{x-playback.channel/track}}` instead do `<radio4000-player track-id="player.currentTrack.ytid">`

**Idea 3:** every `{{track-item}}` needs to know if it's loaded and/or playing. How? We have local prop `isCurrent` as well as `track.isLiveInCurrentPlayer`. But instead we could just do `player.currentTrack.id === trackItemComponent.track.id`?

**Comment by hugurp** [comment]
Ok i see.
As you said it is working at the moment, and it is also a sensitive part.

I'd say let's fix the active state bug on channel.index and move on for now.

As I see it each of these things you point our have a utility at the moment, ofc course it can and should be made better. But the time we invest into this at the moment could be better invested in other aspects of the project.

I am thinking:

1 clarification of the api, deployment scripts, organisation of files (i'm looking at you double package.json) 
2- making api really public, blog post etc. + usage in sharers on ember app
3- making the player accept files as well as youtube links for track provider (which will come in use with r4dl)
4- r4dl offline playlist manager

What's your opinion?
I fear that at the moment I/we are letting our global vision of the projects get blurred by  the sunlight it radiates

**Comment by oskarrough** [comment]
Yes, I agree with you. I'll close this and we can reopen when we want.

But I do think the `originTrack` is just a simply search/replace to fix though? It just got my attention with the duplicate `currentTrack/originTrack` (which aren't synced) — same with `trackItem.isCurrent` and `track.liveInCurrentPlayer` and active class.
