### ISSUE TITLE
Pressing super+enter should submit forms

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#98]
On add track, edit track and more forms it would be nice if the form would be submitted when you press `cmd+enter`. Like on GitHub, and many other places.

Should be ok to do with our `track-form` component + ember-keyboard(which all the others extend)

**Comment by hugurp** [comment]
It works for me on `Ctrl-enter`.

**Comment by oskarrough** [comment]
Wow, yes it does. Nice. Not in Chrome though. Will check if it's on the way…

**Comment by oskarrough** [comment]
Chrome also works with `ctrl+enter` but not `super+enter`. Firefox does both. Good for me. Closing.
